// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroEducativoAPISQL.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20231113133053_mssql_migration_720")]
    partial class mssql_migration_720
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Clase", b =>
                {
                    b.Property<int>("id_clase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_clase"));

                    b.Property<string>("hora_fin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("hora_inicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("id_profesor")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_clase");

                    b.HasIndex("id_profesor");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Comentario", b =>
                {
                    b.Property<int>("id_comentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_comentario"));

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaHoraComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_noticia")
                        .HasColumnType("int");

                    b.Property<string>("id_usuario")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_comentario");

                    b.HasIndex("id_noticia");

                    b.HasIndex("id_usuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Curso", b =>
                {
                    b.Property<int>("id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_curso"));

                    b.Property<string>("aula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion_curso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre_curso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_curso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.CursoClase", b =>
                {
                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdClase")
                        .HasColumnType("int");

                    b.Property<int>("id_curso_clase")
                        .HasColumnType("int");

                    b.HasKey("IdCurso", "IdClase");

                    b.HasIndex("IdClase");

                    b.ToTable("CursoClases");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Nota", b =>
                {
                    b.Property<int>("id_nota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nota"));

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_alumno")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("id_clase")
                        .HasColumnType("int");

                    b.Property<string>("id_docente")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_nota");

                    b.HasIndex("id_alumno");

                    b.HasIndex("id_clase");

                    b.HasIndex("id_docente");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Noticia", b =>
                {
                    b.Property<int>("id_noticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_noticia"));

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_usuario")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parrafos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("redactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_noticia");

                    b.HasIndex("id_usuario");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Pago", b =>
                {
                    b.Property<int>("id_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pago"));

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fecha_pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("fecha_vencimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("id_usuario")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("monto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nro_factura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipo_pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_pago");

                    b.HasIndex("id_usuario");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_rol"));

                    b.Property<string>("tipo_rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id_rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.SolicitudInscripcion", b =>
                {
                    b.Property<int>("id_solicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_solicitud"));

                    b.Property<string>("correoSolicitante")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("fechaNacimientoSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_usuario")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nivelEducativoSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreCompletoSolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_solicitud");

                    b.HasIndex("id_usuario");

                    b.ToTable("SolicitudesInscripcion");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Usuario", b =>
                {
                    b.Property<string>("dni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("dni");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("id_rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.UsuarioClase", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdClase")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_clase")
                        .HasColumnType("int");

                    b.HasKey("Dni", "IdClase");

                    b.HasIndex("IdClase");

                    b.ToTable("UsuariosClases");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.UsuarioCurso", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_curso")
                        .HasColumnType("int");

                    b.HasKey("Dni", "IdCurso");

                    b.HasIndex("IdCurso");

                    b.ToTable("UsuariosCursos");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Clase", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Profesor")
                        .WithMany()
                        .HasForeignKey("id_profesor");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Comentario", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Noticia", "Noticia")
                        .WithMany("Comentarios")
                        .HasForeignKey("id_noticia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Noticia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.CursoClase", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Clase", "Clase")
                        .WithMany("CursoClases")
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroEducativoAPISQL.Modelos.Curso", "Curso")
                        .WithMany("CursoClases")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Nota", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Alumno")
                        .WithMany("NotasComoAlumno")
                        .HasForeignKey("id_alumno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroEducativoAPISQL.Modelos.Clase", "Clase")
                        .WithMany("Notas")
                        .HasForeignKey("id_clase")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Docente")
                        .WithMany("NotasComoDocente")
                        .HasForeignKey("id_docente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Alumno");

                    b.Navigation("Clase");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Noticia", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("Noticias")
                        .HasForeignKey("id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Pago", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.SolicitudInscripcion", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("SolicitudesInscripcion")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Usuario", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Rol", "RolesUsuarios")
                        .WithMany("Usuarios")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.UsuarioClase", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("UsuariosClases")
                        .HasForeignKey("Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroEducativoAPISQL.Modelos.Clase", "Clase")
                        .WithMany("UsuariosClases")
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.UsuarioCurso", b =>
                {
                    b.HasOne("CentroEducativoAPISQL.Modelos.Usuario", "Usuario")
                        .WithMany("UsuariosCursos")
                        .HasForeignKey("Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroEducativoAPISQL.Modelos.Curso", "Curso")
                        .WithMany("UsuariosCursos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Clase", b =>
                {
                    b.Navigation("CursoClases");

                    b.Navigation("Notas");

                    b.Navigation("UsuariosClases");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Curso", b =>
                {
                    b.Navigation("CursoClases");

                    b.Navigation("UsuariosCursos");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Noticia", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CentroEducativoAPISQL.Modelos.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("NotasComoAlumno");

                    b.Navigation("NotasComoDocente");

                    b.Navigation("Noticias");

                    b.Navigation("Pagos");

                    b.Navigation("SolicitudesInscripcion");

                    b.Navigation("UsuariosClases");

                    b.Navigation("UsuariosCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
